### ISSUE TITLE
Return seems to not work

### ISSUE THREAD

**Issue by picarsite** [sandro-pasquali/luau#1]
I have a problem with your code. By the way, thank you for your work. It seems that it is the only node package for redis and lua which works on whole github.
When I am doing that:

`var response = lua.run('setget', 1, 'a', 'qqq');`

I get only that as an answer:
```
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
```

Do I something wrong?

**Comment by sandro-pasquali** [comment]
`luau` returns a Promise (which is what you're seeing).

To get the value you seek, try:

```
lua.run('setget', 1, 'a', 'qqq').then(function(val) {
  console.log(val);
});
```
I apologize, as I see that the docs are not clear on this. I'll spend some time revisiting this library and upgrading the docs.

Thanks!

**Comment by picarsite** [comment]
Thank you, I could get that by myself if it would not be so late. Sorry for this easy question!
